# @package _global_
project: "tuberculosis-montgomeryn"
name: "tb-sz-base-01"
img_size: 512

datamodule:
  _target_: trainer.datamodules.base.DataModuleMontgomery
  data_dir: '/data1/pxi-dataset/cxr/public/tb_montgomery'
  batch_size: 32
  stage: 'train'
  
  
  transforms:
    train:
      resize:
        height: ${img_size}
        width: ${img_size}
        interpolation: 1
      random_flip:
        p: 0.5
      rand_aug_pixel:
        max_n: 4
        channel_stacking: False
        replicate: False
        num_channels: 1
        train: True
        transforms:
          random_blur:
            blur_limit: 15
          random_gamma:
            gamma_limit: 20
          random_clahe:
            clip_limit: 4.0
          random_brightness:
            brightness_limit: 0.2
          random_contrast:
            contrast_limit: 0.2
          random_hist_equal:
            p: 0.5
          random_compression:
            quality_lower: 70
            quality_upper: 100
          random_noise:
            noise_limit: 0.1
          random_bilateral_filter:
            max_d: 5
            sigma_color: 10
            sigma_space: 10
          random_windowing:
            width_param: 4.0
            width_range: 2.0
            use_median: True
      random_spatial_augment_v2:
        n: 2
        height: ${img_size}
        width: ${img_size}
        scale: 0.1
    val:
      resize:
        height: ${img_size}
        width: ${img_size}
        interpolation: 1 # 1:linear, 2:bicubic
  
    test:
      resize:
        height: ${img_size}
        width: ${img_size}
        interpolation: 1 # 1:linear, 2:bicubic


# HRNet48 + fpn + centernet header
model:
  _target_: trainer.src.models.Model
  encoder:
    name: hrnet_w48
    out_indices : [1,2,3,4]
    in_chans: 1
  decoder:
    name: fpn
    feature_aggregation: False
  header:
    name: fcos
    image_size: [768, 768]
    box_format: "xyxy"
    score_thresh: 0.2
    nms_thresh : 0.5
    detections_per_img : 50
          


          

